DEF_CMD_J(SQRT, 2)
DEF_CMD_J(ADD, 2)
DEF_CMD_J(SUB, 2)
DEF_CMD_J(MUL, 2)
DEF_CMD_J(DIV, 2)

DEF_CMD_J(PUSHR_AX, 15)
DEF_CMD_J(PUSHR_BX, 14)
DEF_CMD_J(PUSHR_CX, 14)
DEF_CMD_J(PUSHR_DX, 14)

DEF_CMD_J(POPR_AX, 15)
DEF_CMD_J(POPR_BX, 14)
DEF_CMD_J(POPR_CX, 14)
DEF_CMD_J(POPR_DX, 14)

DEF_CMD_J(IN, 9)
DEF_CMD_J(OUT, 15)
DEF_CMD_J(END, 12)

DEF_CMD_JTWO(JE, 13)
DEF_CMD_JTWO(JNE, 13)
DEF_CMD_JTWO(JA, 13)
DEF_CMD_JTWO(JAE, 13)
DEF_CMD_JTWO(JB,  13)
DEF_CMD_JTWO(JBE, 13)


DEF_CMD_JTWO(CALL, 5)
DEF_CMD_J(RET, 1)
